Added export support for account, instance level vdrs
CloudElementsOpenLabs/the-doctor pull request #18
Opened 2020-02-07 08:25 UTC by ApoorvaTiwari

Supports download of vdrs for accounts and instance level in addition with organization level.

2020-02-11 19:26 UTC, nick-bair commented on src/core/saveCommonResources.js
> +    // const instancesObjectTransformations = await getVdrsObjectsTransformations(vdrName, 'instances', null, instanceId);
@ApoorvaTiwari can you remove the commented out code if it's not needed?

2020-02-13 15:35 UTC, nick-bair approved these changes
Looks good! Thanks :)

2020-05-29 16:43 UTC, Jayme-T commented
@ApoorvaTiwari  this looks good thanks- Please upgrade the package json version and let me know if you want me to merge this or if we were holding off for additional changes

2020-05-29 16:44 UTC, Jayme-T commented
Oh and we will need to pull in master because Mike made some changes and those got merged

2020-06-02 05:06 UTC, Jayme-T requested changes
Hey Apoorva can we submit a version change and pull master into this branch. Then let me know if you want it merged right away or not. Thanks

2020-06-04 06:16 UTC, ApoorvaTiwari commented
Hey Jamie, Pradheep is working on doctor as a service and asked me to hold this until that gets released.

2020-08-17 08:33 UTC, closed without merging

2020-08-17 08:34 UTC, GiriNellore commented
As we handled this with Doctor service changes, closing this PR.