Supported VDR with Both V1 and V2 version for Organisation and Accoun…
CloudElementsOpenLabs/the-doctor pull request #23
Opened 2020-06-04 07:32 UTC by PradheepKumarA

Supported VDR with Both V1 and V2 version for Organisation and Accont level field

2020-06-08 21:50 UTC, Jayme-T requested changes
1- in the package.json  we need the version updated so when we push to npm it is updated. 
2- if the user needs to include any extra parameters or anything then this should be included in an updated readme
3- As far as I can tell it is not working https://a.cl.ly/12uN6dwj

2020-06-09 03:19 UTC, Jayme-T approved these changes

2020-06-09 03:19 UTC, Jayme-T commented
@nick-bair mike was going to take a second review but has not had time, could you please also review this pr

2020-06-09 15:27 UTC, nick-bair approved these changes
Looks good @PradheepKumarA

2020-06-09 15:39 UTC, merged