fix(core): Cancelling the job doesn't cancel the actual process
CloudElementsOpenLabs/the-doctor pull request #53
Opened 2020-10-12 17:25 UTC by MohdRafiUddin

* fix(core): Cancelling the job doesn't cancel the actual process.

2020-10-19 06:28 UTC, GiriNellore requested changes
@MohdRafiUddin Left few comments

2020-10-19 06:28 UTC, GiriNellore commented on src/core/removeCommonResource.js
> +          assetStatus: ArtifactStatus.CANCELLED,
**question:** Why emit this cancelled event from here when this event is already emitted from service? This becomes a circular event emit, and IMO redundant.

2020-10-19 06:28 UTC, GiriNellore commented on src/core/removeElement.js
> +          assetStatus: ArtifactStatus.CANCELLED,
**question:** same question as above

2020-10-20 12:10 UTC, MohdRafiUddin commented on src/core/removeCommonResource.js
> +          assetStatus: ArtifactStatus.CANCELLED,
This is an asset update event.

2020-10-21 07:07 UTC, GiriNellore reviewed
@MohdRafiUddin Looks good except for minor nitpicks.

2020-10-21 07:07 UTC, GiriNellore commented on src/events/emitter.js
> +  JOB_CANCELLED_CORE: 'JOB_CANCELLED_CORE',
**nitpick:** remove this unused item

2020-10-21 07:07 UTC, GiriNellore commented on src/events/cancelled-job.js
> +  } else {
**nitpick:** remove this unused loop

2020-10-21 09:00 UTC, GiriNellore approved these changes

2020-10-21 09:00 UTC, merged